npm run example-ace
npm run example-components
npm run example-driver-io
npm run example-driver-routing
npm run example-driver-websockets
npm run example-effects-aff-ajax
npm run example-effects-eff-random
npm run example-interpret
npm run example-keyboard-input
npm run example-lifecycle
npm run example-multi-component
npm run example-todo
